;; here are packages which have no configuration (we only install & require them)

(use-package command-log-mode :ensure)
(use-package concurrent :ensure)
(use-package cmake-mode :ensure)
(use-package csharp-mode :ensure)
(use-package deferred :ensure)
(use-package diminish :ensure)
(use-package elm-mode :ensure)
(use-package f :ensure)
(use-package font-utils :ensure)
(use-package fringe-helper :ensure)
(use-package fuzzy :ensure)
(use-package magit :ensure)
(use-package powershell :ensure)
(use-package sml-mode :ensure)
