;; here are packages which have no configuration (we only install & require them)

(use-package command-log-mode :ensure)
(use-package concurrent :ensure)
(use-package cmake-mode :ensure  :commands (cmake-mode))
(use-package csharp-mode :ensure :commands (csharp-mode))
(use-package deferred :ensure)
(use-package f :ensure)
(use-package font-utils :ensure)
(use-package fringe-helper :ensure)
(use-package fuzzy :ensure)
(use-package powershell :ensure :commands (powershell-mode))
(use-package sml-mode :ensure :commands (sml-mode))
